### ISSUE TITLE
Locked in the Installer

### ISSUE THREAD

**Issue by biofers** [anklimsk/wpkg-express-2#9]
2 Days looking it to work before started the installer and then more...

Apache2 config LDAP virtual host parameters without nobody can see the website only a 500 error. (conf and 000-default-site)
PHP config sessions.auto_start 1 to work with php7.2 (the installer had a error when it try to create the database)

Finally I see that the error from the database creation it´s not there anymore with the change in the php.ini.
I start again sudo ./Console/cake CakeInstaller install
The process always ask me to drop and create the tables and schemas... yet without error but always ask it for, it doen´t check it I done before...

"Intsall Completed"
"The installation process is completed unsuccessful" (From Where??)

Now I can see the web (with login from the Domain) but only load the check web, it isn´t finish right the installation... Whatever I do I stuck it . I check the database, the tables are there.

**Comment by anklimsk** [comment]
Good day. Fixed in a new release: [v1.0.10-rc.1](https://github.com/anklimsk/wpkg-express-2/releases/tag/v1.0.10-rc.1)

**Comment by biofers** [comment]
still not working for me...

APT from everything need it, i think, apache2, php, mysql-server, php-ldap, php-bz2, php-mysql. every check in the installer ok, but again the database... or the permission to open the project.

apache2
<Directory "/var/www/wpkg/app/webroot">
	Options Indexes FollowSymLinks MultiViews
	AllowOverride All
	Order deny,allow
	Allow from all
</Directory>
Then mod rewrite something work because rewrite me the URL but the page not load.
The website tell me that I don't have permission to open..... chmod 755 -r /var/www/wpkg not solved...
(new installation Ubuntu or Debian last versions LST)

and then the installer to create the Database (that we have to made it manually from mysql the installer failed when the database is not in the mysql server)..........

I was for a moment a good new that you return to this project but tell me if I can help you more.

then the message errors.

```
> `Are you sure you want to drop the table(s)? (y/n) 
> [n] > n
> Are you sure you want to create the table(s)? (y/n) 
> [y] > y
> Error: Table queued_tasks for model ExtendQueuedTask was not found in datasource default.
> #0 /var/www/wpkg/lib/Cake/Model/Model.php(3686): Model->setSource('queued_tasks')
> #1 /var/www/wpkg/app/Model/AppModel.php(135): Model->getDataSource()
> #2 /var/www/wpkg/app/Model/AppModel.php(150): AppModel->_getDataSourceName()
> #3 /var/www/wpkg/app/Model/ExtendQueuedTask.php(47): AppModel->isDataSourceMysql()
> #4 [internal function]: ExtendQueuedTask->__construct(Array)
> #5 /var/www/wpkg/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
> #6 /var/www/wpkg/app/Model/Behavior/GroupActionBehavior.php(65): ClassRegistry::init('ExtendQueuedTas...')
> #7 /var/www/wpkg/lib/Cake/Model/BehaviorCollection.php(145): GroupActionBehavior->setup(Object(Archive), Array)
> #8 /var/www/wpkg/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('GroupAction', Array)
> #9 /var/www/wpkg/lib/Cake/Model/Model.php(781): BehaviorCollection->init('Archive', Array)
> #10 /var/www/wpkg/app/Plugin/Shim/Model/ShimModel.php(26): Model->__construct(NULL, NULL, 'default')
> #11 [internal function]: ShimModel->__construct(Array)
> #12 /var/www/wpkg/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
> #13 /var/www/wpkg/app/Plugin/CakeInstaller/Model/InstallerInit.php(52): ClassRegistry::init('Archive', true)
> #14 /var/www/wpkg/app/Config/Schema/schema.php(60): InstallerInit->initDbTable('archives')
> #15 /var/www/wpkg/lib/Cake/Console/Command/SchemaShell.php(448): AppSchema->after(Array)
> #16 /var/www/wpkg/lib/Cake/Console/Command/SchemaShell.php(351): SchemaShell->_run(Array, 'create', Object(AppSchema))
> #17 /var/www/wpkg/lib/Cake/Console/Command/SchemaShell.php(250): SchemaShell->_create(Object(AppSchema), 'wpi_categories')
> #18 /var/www/wpkg/lib/Cake/Console/Shell.php(459): SchemaShell->create()
> #19 /var/www/wpkg/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('create', Array)
> #20 /var/www/wpkg/lib/Cake/Console/Shell.php(399): ShellDispatcher->dispatch()
> #21 /var/www/wpkg/app/Plugin/CakeInstaller/Console/Command/CakeInstallerShell.php(649): Shell->dispatchShell('schema create -...')
> #22 /var/www/wpkg/app/Plugin/CakeInstaller/Console/Command/CakeInstallerShell.php(250): CakeInstallerShell->_createdb()
> #23 /var/www/wpkg/lib/Cake/Console/Shell.php(462): CakeInstallerShell->main()
> #24 /var/www/wpkg/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand(NULL, Array)
> #25 /var/www/wpkg/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
> #26 /var/www/wpkg/app/Console/cake.php(47): ShellDispatcher::run(Array)
> #27 {main}
> `

```

One thing more, in one combination or drop the database and create manually i finish without error the installer but at the end was unsuccessfull......

**Comment by biofers** [comment]
Last report, few hours later I have it. when the installer ask me to make the first table of the database I said N and N and then I created the second and third part. Then I created the first table again without error... everythings is pretty much like I'm looking to admin a little more wpkg.

I like it, if you want to add something more look https://wpkg.org/Packages.xml#Action_conditions, I have a few 

```
XML failed to pass XSD schema validation
Errors:
Element 'condition': This element is not expected. (line 35)
Element 'condition': This element is not expected. (line 41)
```

Thanks very much.
